version: "3"
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: Spring6
      MYSQL_ROOT_PASSWORD: '19960214At313!'
    volumes:
      - ~/Ahsoka/sql-dumps:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p19960214At313!" ]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Spring6
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 19960214At313!

volumes:
  dbdata: {}